[project]
name = "journey-of-soup"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pygame >= 2.6.0"
    ]

[project.optional-dependencies]
dev = ["pytest"]

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
py-modules = [
    "main",
    "classes"
]

[tool.pytest.ini_options]
testpaths = ["test"]
pythonpath = ["src"]
filterwarnings =[
    "ignore:pkg_resources is deprecated:UserWarning",
]